name: Deploy test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@main

    - name: test-deploy
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
    - run: dotnet build TwoSum.csproj